version: '3.8'

services:
  newsbot:
    build: .
    container_name: newsbot
    env_file:
      - .env
    volumes:
      - ./posted_titles.txt:/app/posted_titles.txt
      - ./posted_hashes.txt:/app/posted_hashes.txt
      - ./rss_feeds.txt:/app/rss_feeds.txt
      - ./prompt.txt:/app/prompt.txt
      - ./newsbot.log:/app/newsbot.log
    command: >
      sh -c "while true; do python main.py; sleep 3600; done"
    restart: unless-stopped