version: '3.8'
services:
  rss2wp:
    build: .
    container_name: rss2wp
    restart: always
    env_file: .env
    volumes:
      - ./posted_titles.txt:/app/posted_titles.txt
    command: >
      sh -c "while true; do python app.py; sleep 3600; done"
